### ISSUE TITLE
cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by asenawritescode** [VerifiedJoseph/ntfy-php-library#122]
Hey the new version came with that error.
cURL error 60: SSL certificate problem: certificate has expired (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://ntfy.sh/

You can replicate it by using laragon and the library on a windows machine

**Comment by VerifiedJoseph** [comment]
I've been unable to replicate this using Laragon. looks like the certificate has been replaced.

**Comment by asenawritescode** [comment]
> I've been unable to replicate this using Laragon. looks like the certificate has been replaced.

I do not understand  because I am still getiing the same error.
How can I switch up to use a different service from cUrl ?

**Comment by asenawritescode** [comment]
https://medium.com/@narendravaghela/how-to-fix-curl-error-60-ssl-certificate-problem-80e7dafafa57
 I have able to add the new certificate manually.
 Thank you.
