### ISSUE TITLE
Support for markdown

### ISSUE THREAD

**Issue by zajinx** [VerifiedJoseph/ntfy-php-library#291]
Can you please add support for markdown messages?

Thank you,

https://docs.ntfy.sh/publish/#publish-as-json

**Comment by VerifiedJoseph** [comment]
Thank you for this request. Markdown support is now available in version 4.4.0.  

Code example: https://github.com/VerifiedJoseph/ntfy-php-library/blob/main/examples/send-message-with-markdown-body.php
