### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by inverse** [VerifiedJoseph/ntfy-php-library#99]
Is there a reason for targeting PHP 8 vs 7.4 here? I can't see anything in the code that targets 8?

**Comment by VerifiedJoseph** [comment]
I can't think of a specific reason other than PHP 8 being installed on my setup when starting this project. Given that support for 7.4 [ends in November](https://www.php.net/supported-versions.php), I'm not partially interested in lowering the minimum version to 7.4.

**Comment by inverse** [comment]
Fair enough - yeah it's becoming EOL pretty soon.

Found out when trying to integrate it into https://github.com/inverse/termin/pull/74
